"""
Rules generation logic for the Motif CLI.

Takes analysis JSON output (from the host agent) and generates configuration files:
CLAUDE.md, skill files, and optionally .cursorrules.
"""

import json
import re
from pathlib import Path


def load_analysis(path: str) -> dict:
    """Load and validate analysis JSON from a file path.

    Handles both raw JSON files and the case where JSON is embedded in
    markdown (extracts JSON from ```json ... ``` code fences if needed).

    Args:
        path: Path to the analysis file (JSON or markdown with embedded JSON).

    Returns:
        Parsed analysis dict with defaults for missing top-level keys.

    Raises:
        FileNotFoundError: If the file does not exist.
        json.JSONDecodeError: If no valid JSON can be extracted.
    """
    p = Path(path)
    if not p.exists():
        raise FileNotFoundError(f"Analysis file not found: {path}")

    text = p.read_text(encoding="utf-8")

    # Try direct JSON parse first
    try:
        return _validate_analysis(json.loads(text))
    except json.JSONDecodeError:
        pass

    # Extract JSON from markdown code fences
    match = re.search(r"```(?:json)?\s*\n([\s\S]*?)\n```", text)
    if match:
        try:
            return _validate_analysis(json.loads(match.group(1)))
        except json.JSONDecodeError as e:
            raise json.JSONDecodeError(
                f"Invalid JSON in markdown code fence: {e.msg}",
                e.doc,
                e.pos,
            ) from e

    raise json.JSONDecodeError(
        "No valid JSON found. Expected raw JSON or JSON in ```json ... ``` code fence.",
        text,
        0,
    )


def _validate_analysis(data: dict) -> dict:
    """Ensure analysis has all expected top-level keys with defaults."""
    defaults = {
        "skills": [],
        "rules": [],
        "communication_style": {},
        "session_patterns": {},
        "improvement_areas": [],
        "project_context": {},
    }
    result = {**defaults, **data}

    # Normalize nested dicts
    if not isinstance(result.get("communication_style"), dict):
        result["communication_style"] = {}
    if not isinstance(result.get("session_patterns"), dict):
        result["session_patterns"] = {}
    if not isinstance(result.get("project_context"), dict):
        result["project_context"] = {}

    return result


def generate_claude_md(analysis: dict, project_name: str = "this project") -> str:
    """Generate a CLAUDE.md file from the analysis.

    Args:
        analysis: Parsed analysis dict from load_analysis.
        project_name: Name of the project for the header.

    Returns:
        Full CLAUDE.md content as a string.
    """
    lines = [
        "# CLAUDE.md",
        "",
        "*Generated by Motif — review and customize for your workflow.*",
        "",
    ]

    # Project Overview
    ctx = analysis.get("project_context") or {}
    desc = ctx.get("description", "").strip()
    if desc:
        lines.extend(["## Project Overview", "", desc, ""])
        entities = ctx.get("key_entities") or []
        if entities:
            lines.append("**Key entities:** " + ", ".join(entities))
            lines.append("")
        tools = ctx.get("tools_used") or []
        if tools:
            lines.append("**Tools used:** " + ", ".join(tools))
            lines.append("")
    else:
        lines.extend(["## Project Overview", "", f"Guidance for {project_name}.", ""])

    # Communication Style
    comm = analysis.get("communication_style") or {}
    if any(comm.values()):
        lines.extend(["## Communication Style", ""])
        for key, val in comm.items():
            if val:
                label = key.replace("_", " ").title()
                lines.append(f"- **{label}:** {val}")
        lines.append("")

    # Agent Behavior / Rules
    rules = analysis.get("rules") or []
    included_rules = [
        r for r in rules
        if (r.get("confidence") or "low") in ("high", "medium")
    ]
    if included_rules:
        lines.extend(["## Agent Behavior", ""])
        project_rules = [r for r in included_rules if (r.get("scope") or "project").strip() == "project"]
        user_rules = [r for r in included_rules if (r.get("scope") or "project").strip() == "user"]
        if project_rules and user_rules:
            lines.extend(["### Rules", ""])
            for i, r in enumerate(project_rules, 1):
                enforces = r.get("enforces", "").strip()
                if enforces:
                    lines.append(f"{i}. {enforces}")
            lines.extend(["", "### User Preferences", ""])
            for i, r in enumerate(user_rules, 1):
                enforces = r.get("enforces", "").strip()
                if enforces:
                    lines.append(f"{i}. {enforces}")
        else:
            lines.extend(["### Rules", ""])
            for i, r in enumerate(included_rules, 1):
                enforces = r.get("enforces", "").strip()
                if enforces:
                    lines.append(f"{i}. {enforces}")
        lines.append("")
        lines.extend([
            "### Subagent Delegation",
            "",
            "Prefer delegating to subagents for complex, multi-step tasks. This prevents overloading the main context window and improves quality.",
            "",
            "**When to delegate:** Tasks with 3+ distinct steps, research-heavy work, parallel workstreams, skill file generation.",
            "**Model selection:** Use fast model for coding tasks, file edits, and implementation. Use default model for planning and architecture.",
            "",
        ])

    # Workflow Triggers
    skills = analysis.get("skills") or []
    if skills:
        lines.extend(["## Workflow Triggers", ""])
        lines.append("| When you're... | Load this file |")
        lines.append("|---|---|")
        for s in skills:
            trigger = (s.get("trigger") or "").strip()
            name = (s.get("name") or "unnamed").strip()
            scope = s.get("scope", "project")
            if scope == "user":
                path = f"~/.cursor/skills/{_slug(name)}/SKILL.md"
            else:
                path = f".cursor/skills/{_slug(name)}/SKILL.md"
            lines.append(f"| {trigger or '(no trigger)'} | `{path}` |")
        lines.append("")

    # Session Patterns
    sess = analysis.get("session_patterns") or {}
    if any(sess.values()):
        lines.extend(["## Session Patterns", ""])
        startup = sess.get("startup", "").strip()
        wrapup = sess.get("wrapup", "").strip()
        if startup:
            lines.append(f"- **Startup:** {startup}")
        if wrapup:
            lines.append(f"- **Wrapup:** {wrapup}")
        evidence = sess.get("evidence") or []
        if evidence:
            lines.append("- **Evidence:**")
            for e in evidence[:3]:
                if e:
                    lines.append(f"  - {e}")
        lines.append("")

    # Improvement Areas
    improvements = analysis.get("improvement_areas") or []
    if improvements:
        lines.extend(["## Improvement Areas", ""])
        for imp in improvements:
            problem = (imp.get("problem") or "").strip()
            proposed = (imp.get("proposed_rule") or "").strip()
            if problem:
                lines.append(f"- **{problem}**")
                if proposed:
                    lines.append(f"  - Proposed rule: {proposed}")
        lines.append("")

    # Pre-Completion Checklist (from improvement_areas proposed_rules)
    proposed_rules = [
        (imp.get("proposed_rule") or "").strip()
        for imp in improvements
        if (imp.get("proposed_rule") or "").strip()
    ]
    if proposed_rules:
        lines.extend(["## Pre-Completion Checklist", ""])
        lines.append("Before finishing work, verify:")
        for pr in proposed_rules:
            lines.append(f"- [ ] {pr}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _slug(name: str) -> str:
    """Convert skill name to a filesystem-safe slug."""
    return "".join(c if c.isalnum() or c in "-_" else "-" for c in name.lower()).strip("-")


def generate_skill_file(skill: dict) -> str:
    """Generate a single skill SKILL.md from a skill dict.

    Supports both legacy (steps) and new (instructions) field names.
    Handles optional fields: purpose, when_to_use, best_practices,
    common_pitfalls, key_constraints, evidence, confidence, etc.

    Args:
        skill: Skill dict with name, trigger, purpose, when_to_use,
            instructions/steps, best_practices, common_pitfalls,
            key_constraints, evidence, confidence, scope, etc.

    Returns:
        Full SKILL.md content as a string.
    """
    name = (skill.get("name") or "unnamed").strip()
    trigger = (skill.get("trigger") or "").strip()
    purpose = (skill.get("purpose") or "").strip()
    when_to_use = skill.get("when_to_use") or []
    instructions = skill.get("instructions") or skill.get("steps") or []
    best_practices = skill.get("best_practices") or []
    common_pitfalls = skill.get("common_pitfalls") or []
    key_constraints = skill.get("key_constraints") or []
    evidence = skill.get("evidence") or []
    confidence = str(skill.get("confidence") or "low").strip()
    scope = str(skill.get("scope") or "project").strip()

    slug = _slug(name)
    title = name.replace("-", " ").replace("_", " ").title()
    desc_text = purpose or trigger or "Workflow skill discovered by Motif"
    desc_text = desc_text.rstrip(".")
    description = f"{desc_text}. [GENERATED BY MOTIF — review and customize]"

    lines = [
        "---",
        f"name: {slug}",
        f'description: "{description}"',
        "---",
        "",
        f"# {title}",
        "",
        purpose or "Workflow skill discovered by Motif.",
        "",
        "## When to Use",
        "",
    ]

    if when_to_use:
        for item in when_to_use:
            if item:
                lines.append(f"- {item}")
    else:
        lines.append(f"- {trigger}" if trigger else "- (Add when to use this skill)")

    lines.extend(["", "## Instructions", ""])

    for i, step in enumerate(instructions, 1):
        step_str = str(step).strip()
        if " -> " in step_str or " -- " in step_str:
            parts = re.split(r"\s+->\s+|\s+--\s+", step_str)
            lines.append(f"{i}. {parts[0].strip()}")
            for p in parts[1:]:
                if p.strip():
                    lines.append(f"   - {p.strip()}")
        else:
            lines.append(f"{i}. {step_str}")
    if not instructions:
        lines.append("1. (Add steps based on your workflow)")

    if best_practices:
        lines.extend(["", "## Best Practices", ""])
        for bp in best_practices:
            if bp:
                bp_str = str(bp).strip()
                if bp_str.lower().startswith(("don't", "do not", "avoid", "never")):
                    lines.append(f"- **Avoid:** {bp_str}")
                else:
                    lines.append(f"- {bp_str}")

    if common_pitfalls:
        lines.extend(["", "## Common Pitfalls", ""])
        lines.append("| Problem | Solution |")
        lines.append("|---|---|")
        for cp in common_pitfalls:
            if isinstance(cp, dict):
                prob = (cp.get("problem") or "").strip()
                sol = (cp.get("solution") or "").strip()
                if prob or sol:
                    lines.append(f"| {prob} | {sol} |")
            elif cp:
                lines.append(f"| {cp} | (Add solution) |")

    lines.extend(["", "## Key Constraints", ""])
    if key_constraints:
        for kc in key_constraints:
            if kc:
                lines.append(f"- {kc}")
    else:
        lines.append(f"- Confidence: {confidence}")
        if evidence:
            lines.append(f"- Evidence: {evidence[0]}")
        lines.append(f"- Scope: {scope}")

    return "\n".join(lines) + "\n"


def generate_all(
    analysis: dict,
    output_dir: Path,
    project_name: str = "this project",
) -> dict[str, str]:
    """Generate all files to the output directory.

    Creates CLAUDE.md and skills/{scope}/{skill-name}/SKILL.md for each skill.
    Scope (project/user) is encoded in the path for deploy_files routing.

    Args:
        analysis: Parsed analysis dict.
        output_dir: Directory to write generated files (staging).
        project_name: Project name for CLAUDE.md.

    Returns:
        Dict of {relative_path: content} for all generated files.
    """
    output_dir = Path(output_dir)
    generated: dict[str, str] = {}

    # CLAUDE.md
    claude_content = generate_claude_md(analysis, project_name)
    generated["CLAUDE.md"] = claude_content

    # Skills
    skills = analysis.get("skills") or []
    for skill in skills:
        scope = (skill.get("scope") or "project").strip()
        name = (skill.get("name") or "unnamed").strip()
        slug = _slug(name)
        rel_path = f"skills/{scope}/{slug}/SKILL.md"
        generated[rel_path] = generate_skill_file(skill)

    return generated


def preview_generation(analysis: dict) -> str:
    """Return a human-readable summary of what would be generated (for --dry-run).

    Args:
        analysis: Parsed analysis dict.

    Returns:
        Summary string with counts and file names.
    """
    lines = [
        "## Generation Preview",
        "",
        "**Would generate:**",
        "",
    ]

    # CLAUDE.md
    lines.append("- `CLAUDE.md`")

    # Skills
    skills = analysis.get("skills") or []
    if skills:
        lines.append(f"- `skills/` ({len(skills)} skills):")
        for s in skills:
            scope = s.get("scope", "project")
            name = s.get("name", "unnamed")
            slug = _slug(name)
            lines.append(f"  - `skills/{scope}/{slug}/SKILL.md` ({name})")
    else:
        lines.append("- No skills")

    # Counts
    rules = analysis.get("rules") or []
    included_rules = [r for r in rules if (r.get("confidence") or "low") in ("high", "medium")]
    lines.extend([
        "",
        "**Summary:**",
        f"- {len(included_rules)} rules (high/medium confidence)",
        f"- {len(skills)} skills",
        f"- {len(analysis.get('improvement_areas') or [])} improvement areas",
    ])

    return "\n".join(lines) + "\n"


def deploy_files(
    generated_files: dict[str, str],
    output_dir: Path,
    project_dir: Path | None = None,
) -> list[str]:
    """Copy generated files from staging to their deployment locations.

    Project-scoped items go to project_dir/.cursor/
    User-scoped items go to ~/.cursor/

    Reads file content from output_dir (staging). If a file is missing in
    staging, falls back to content from generated_files dict when available.

    Args:
        generated_files: Dict of {relative_path: content} from generate_all.
        output_dir: Staging directory where files were written.
        project_dir: Project root for project-scoped files. If None, use cwd.

    Returns:
        List of deployed absolute paths.
    """
    output_dir = Path(output_dir)
    project_dir = Path(project_dir) if project_dir else Path.cwd()
    user_cursor = Path.home() / ".cursor"
    deployed: list[str] = []

    for rel_path in generated_files:
        parts = rel_path.replace("\\", "/").split("/")
        src = output_dir / rel_path

        # Prefer reading from staging; fall back to dict content
        if src.exists():
            content = src.read_text(encoding="utf-8")
        else:
            content = generated_files.get(rel_path, "")

        if rel_path == "CLAUDE.md":
            dest = project_dir / "CLAUDE.md"
        elif len(parts) >= 3 and parts[0] == "skills":
            scope = parts[1]  # "project" or "user"
            skill_name = parts[2]
            if scope == "user":
                dest = user_cursor / "skills" / skill_name / "SKILL.md"
            else:
                dest = project_dir / ".cursor" / "skills" / skill_name / "SKILL.md"
        else:
            dest = output_dir / rel_path

        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content, encoding="utf-8")
        deployed.append(str(dest.resolve()))

    return deployed
