"""
Markdown report generation for Motif CLI.

Takes analysis JSON output and produces a formatted markdown report.
Handles missing or empty fields gracefully by skipping sections.
"""

from typing import Any


def _safe_get(obj: dict, key: str, default: Any = None) -> Any:
    """Return obj[key] if present and non-empty, else default."""
    val = obj.get(key, default)
    if val is None or val == "":
        return default
    return val


def _safe_list(lst: list | None) -> list:
    """Return lst if it's a non-empty list, else empty list."""
    if not lst or not isinstance(lst, list):
        return []
    return lst


def _first(items: list, default: str = "") -> str:
    """Return first item or default if empty."""
    return items[0] if items else default


def _comma_join(items: list[str]) -> str:
    """Join non-empty strings with commas."""
    return ", ".join(str(x).strip() for x in items if x)


def _count_confidence(items: list[dict], level: str) -> int:
    """Count items with given confidence level."""
    return sum(1 for i in items if (i.get("confidence") or "").lower() == level)


def generate_report(analysis: dict, project_name: str = "Unknown Project") -> str:
    """Generate a full markdown report from analysis JSON.

    Args:
        analysis: Parsed analysis output with keys: skills, rules,
            communication_style, session_patterns, improvement_areas,
            project_context. Missing or empty sections are skipped.
        project_name: Display name for the project in the report header.

    Returns:
        Formatted markdown string.
    """
    lines: list[str] = []

    skills = _safe_list(analysis.get("skills"))
    rules = _safe_list(analysis.get("rules"))
    improvement_areas = _safe_list(analysis.get("improvement_areas"))
    comm_style = analysis.get("communication_style") or {}
    session_patterns = analysis.get("session_patterns") or {}
    project_context = analysis.get("project_context") or {}

    high_count = _count_confidence(skills, "high")
    med_count = _count_confidence(skills, "medium")

    # Header
    lines.append(f"# Motif Analysis Report: {project_name}")
    lines.append("")
    lines.append("*Generated by [Motif](https://github.com/avivsheriff/motif-cli)*")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Summary
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- **{len(skills)} skills** discovered ({high_count} high confidence, {med_count} medium)")
    lines.append(f"- **{len(rules)} rules** identified")
    lines.append(f"- **{len(improvement_areas)} improvement areas** flagged")
    lines.append("")

    # Project Context
    desc = _safe_get(project_context, "description")
    key_entities = _safe_list(project_context.get("key_entities"))
    tools_used = _safe_list(project_context.get("tools_used"))

    if desc or key_entities or tools_used:
        lines.append("## Project Context")
        lines.append("")
        if desc:
            lines.append(desc)
            lines.append("")
        if key_entities or tools_used:
            if key_entities:
                lines.append(f"**Key entities:** {_comma_join(key_entities)}")
            if tools_used:
                lines.append(f"**Tools:** {_comma_join(tools_used)}")
            lines.append("")
        lines.append("---")
        lines.append("")

    # Discovered Skills
    if skills:
        lines.append("## Discovered Skills")
        lines.append("")
        for s in skills:
            name = _safe_get(s, "name", "Unnamed skill")
            confidence = _safe_get(s, "confidence", "—")
            scope = _safe_get(s, "scope", "—")
            trigger = _safe_get(s, "trigger", "—")
            frequency = _safe_get(s, "frequency", "—")
            steps = _safe_list(s.get("steps"))
            evidence = _safe_list(s.get("evidence"))

            lines.append(f"### {name} ({confidence}, {scope})")
            lines.append("")
            lines.append(f"**Trigger:** {trigger}")
            lines.append(f"**Frequency:** {frequency}")
            lines.append("")
            if steps:
                lines.append("Steps:")
                for i, step in enumerate(steps, 1):
                    lines.append(f"{i}. {step}")
                lines.append("")
            if evidence:
                lines.append(f'> Evidence: "{_first(evidence)}"')
            lines.append("")
            lines.append("---")
            lines.append("")

    # Identified Rules
    if rules:
        lines.append("## Identified Rules")
        lines.append("")
        for r in rules:
            name = _safe_get(r, "name", "Unnamed rule")
            confidence = _safe_get(r, "confidence", "—")
            scope = _safe_get(r, "scope", "—")
            enforces = _safe_get(r, "enforces", "")
            evidence = _safe_list(r.get("evidence"))

            lines.append(f"### {name} ({confidence}, {scope})")
            lines.append("")
            if enforces:
                lines.append(enforces)
                lines.append("")
            if evidence:
                lines.append(f'> Evidence: "{_first(evidence)}"')
            lines.append("")
            lines.append("---")
            lines.append("")

    # Communication Style
    brevity = _safe_get(comm_style, "brevity", "—")
    feedback = _safe_get(comm_style, "feedback_pattern", "—")
    correction = _safe_get(comm_style, "correction_style", "—")
    proactivity = _safe_get(comm_style, "proactivity_expectation", "—")

    if any(x != "—" for x in (brevity, feedback, correction, proactivity)):
        lines.append("## Communication Style")
        lines.append("")
        lines.append("| Aspect | Pattern |")
        lines.append("|--------|---------|")
        lines.append(f"| Brevity | {brevity} |")
        lines.append(f"| Feedback | {feedback} |")
        lines.append(f"| Corrections | {correction} |")
        lines.append(f"| Proactivity | {proactivity} |")
        lines.append("")

    # Session Patterns
    startup = _safe_get(session_patterns, "startup")
    wrapup = _safe_get(session_patterns, "wrapup")
    if startup or wrapup:
        lines.append("## Session Patterns")
        lines.append("")
        lines.append(f"**Startup:** {startup or '—'}")
        lines.append(f"**Wrap-up:** {wrapup or '—'}")
        lines.append("")

    # Improvement Opportunities
    if improvement_areas:
        lines.append("## Improvement Opportunities")
        lines.append("")
        for area in improvement_areas:
            problem = _safe_get(area, "problem", "—")
            proposed_rule = _safe_get(area, "proposed_rule", "")
            evidence = _safe_list(area.get("evidence"))

            lines.append(f"### {problem}")
            lines.append("")
            if proposed_rule:
                lines.append(f"**Proposed rule:** {proposed_rule}")
                lines.append("")
            if evidence:
                lines.append(f"> {_first(evidence)}")
            lines.append("")

    # What Was Generated
    lines.append("---")
    lines.append("")
    lines.append("## What Was Generated")
    lines.append("")
    skill_names = [_safe_get(s, "name", "") for s in skills if _safe_get(s, "name")]
    skill_names_str = _comma_join(skill_names) if skill_names else "—"

    lines.append(f"- `CLAUDE.md` — Project context, communication style, {len(rules)} rules, workflow triggers")
    lines.append(f"- {len(skills)} skill files — {skill_names_str}")

    return "\n".join(lines).rstrip()
